### ISSUE TITLE
hardware specifications for redis benchmark

### ISSUE THREAD

**Issue by TOMATOFQY** [arceos-org/arceos#124]
Hello, I am amazed by the redis running on arceos. This is fantastic work. However, I didn't see the hardware specifications for the benchmark in the README file under the apps/c/redis directory (it could also be that I overlooked it). I only saw that the tests were conducted under 2GB of memory size. Could you please provide additional details such as the specific CPU model, clock speed, and other relevant specifications?

**Comment by equation314** [comment]
Hello, thanks for your feedback.

You can use the following command to run redis in QEMU:

```shell
make A=apps/c/redis/ LOG=error NET=y BLK=y ARCH=aarch64 SMP=4 run
make A=apps/c/redis/ LOG=error NET=y BLK=y ARCH=x86_64 SMP=4 run
```

For bare-metal hardwares, the only requirement is Intel 82599 NIC, other parameters like clock speed are not specific, but they should be provided in the specification file in the `platforms` directory.
