### ISSUE TITLE
The rust-fatfs log error

### ISSUE THREAD

**Issue by Godones** [arceos-org/arceos#128]
I am running the shell app. If I use cargo update to update the dependencies, log-related errors will appear in the rust-fatfs library.
<img width="783" alt="image" src="https://github.com/rcore-os/arceos/assets/57819926/3de841f7-73bc-43e4-9b3c-5a0e2e7902b0">

This error is because this library has customized its own log-related macros, but the current version is no longer applicable. Is it possible to re-fork this library and make modifications?

**Comment by equation314** [comment]
Make sure the version of the `log` crate is exactly `0.4.19` in `Cargo.lock`.
