### ISSUE TITLE
Building errors when I try to run the apps by cmake.

### ISSUE THREAD

**Issue by zmhab** [arceos-org/arceos#131]
![Screenshot 2023-10-25 200344_issue](https://github.com/rcore-os/arceos/assets/33960416/ad1c8a3a-edca-4582-a04c-ab0a75e20638)
Show as the image, when I run the apps(helloworld), the cargo building system shows the error messages about missing _rust -objcopy_ libs. How can I solve this problem?

**Comment by equation314** [comment]
Please execute `cargo install cargo-binutils` to install it.

**Comment by zmhab** [comment]
It woks. Thank you!

**Comment by zmhab** [comment]
By the way, I clone the repository to Gitee. [Click here](https://gitee.com/zhanghongming0131/arceos) I hope it can give some help to build our _Version Control System_, like Git platform.
