### ISSUE TITLE
Can not run the Display example app.

### ISSUE THREAD

**Issue by zmhab** [arceos-org/arceos#132]
![image](https://github.com/rcore-os/arceos/assets/33960416/52fa1396-f042-48ce-be42-05933d0434c3)
Hi,
Show as the image, I ran the Display app on Ubuntu Server platform at first time, but it don't display any graphical interface. So I run it on Deepin Desktop platform later, and it also has same error. Why?
I have run all apps successfully so far except Display, Net and C apps. I guess the reason that I can't run the C apps successfully is also _there aren't necessary libs_ from information what I get in error logs.
At last, by the way, I plan to check for mirror repository updates per day from GitHub repository and will sync from it if necessary.

**Comment by equation314** [comment]
You are using the VNC backend for QEMU graphical output. You can use a VNC client to see it, or use gtk backend by the argument `-display gtk`.

**Comment by zmhab** [comment]
Thanks. I run it successfully by TigerVNC_Viewer, show as the image:
![Screenshot 2023-10-31 205618](https://github.com/rcore-os/arceos/assets/33960416/2c936d48-d482-4889-b67e-ad84fe71cfef)
But another question is that why can't I run the C apps? Show error logs as the image:
![Screenshot 2023-10-31 210811](https://github.com/rcore-os/arceos/assets/33960416/365bb083-9198-452f-9d9f-71fd838b0146)

**Comment by equation314** [comment]
You need to install `libclang`, see https://github.com/rcore-os/arceos#for-buildrun-c-apps.

**Comment by zmhab** [comment]
Excellent! I run it successfully after install `libclang` (Oh, no! I ignore it when I read the documentation at first time...). Show as the image:
![image](https://github.com/rcore-os/arceos/assets/33960416/d918f3e1-bf34-466b-a226-0096921579fb)
Then I will try to run the Net apps, and I will create new issue if it has any problem.
Thanks.
