### ISSUE TITLE
How to run it on Mac OS?

### ISSUE THREAD

**Issue by leer168** [arceos-org/arceos#141]

**Comment by equation314** [comment]
Please give us more details, like the CPU (intel or Apple Silicon), what app you want to run, and why it doesn't run on your computer.

**Comment by leer168** [comment]
Thank you for reply!

I follow the tutorial to study, eg. https://rcore-os.cn/arceos-tutorial-book/ch01-01.html or https://rcore-os.cn/rCore-Tutorial-Book-v3/index.html. Neither mentioned how to run it on MacOS.

![image](https://github.com/rcore-os/arceos/assets/934063/c435f71c-a678-418c-9709-919d9807c018)

**Comment by equation314** [comment]
The steps to run on macOS are similar to those on linux, please refer to README, but you need to install the corresponding toolchain (e.g., QEMU) for macOS.

**Comment by leer168** [comment]
![image](https://github.com/rcore-os/arceos/assets/934063/7163253f-5f5a-4aa5-82d9-d069f4384fc7)

After an afternoon, the hello app was successfully run.

![image](https://github.com/rcore-os/arceos/assets/934063/2e5bc906-9f3e-4c3d-8a12-48ff31264ad0)
But qemu-riscv64 was not compiled, so I don’t know what impact this will have.

Configuration steps on MacOS
1. curl https://sh.rustup.rs -sSf | sh
2. cargo install cargo-binutils
3. brew install qemu will failed, so compile from source code:
3.1  brew install libffi gettext glib pkg-config pixman ninja meson // reference https://wiki.qemu.org/Hosts/Mac - Building QEMU for macOS
3.2  tar xvJf qemu-7.0.0.tar.xz
3.3 ./configure --target-list=riscv64-softmmu
3.4 make
4. git clone https://github.com/rcore-os/arceos.git
5. make ARCH=riscv64 A=apps/helloworld run

Thank you again!!!

**Comment by equation314** [comment]
QEMU 8.2.1 was provided by the latest homebrew, which includes `qemu-system-riscv64`. You may need to update your `brew` version.

**Comment by equation314** [comment]
`qemu-riscv64` was only available on Linux, which requires Linux syscalls.
