### ISSUE TITLE
Request to Publish `axalloc` Crate on crates.io

### ISSUE THREAD

**Issue by memN0ps** [arceos-org/arceos#156]
Hi Arceos,

Cool projects.

Could I please request that you put the `axalloc` crate on crates.io if possible?

Currently, I have to use it like this:

```
## Custom Allocator Dependencies
spinlock = { git = "https://github.com/arceos-org/arceos" }
memory_addr = { git = "https://github.com/arceos-org/arceos" }
allocator = { git = "https://github.com/arceos-org/arceos" , features = ["bitmap", "slab"] }
axerrno = { git = "https://github.com/arceos-org/arceos" }
```

Then add `lib.rs` and `page.rs` from `axalloc`.

Regards,

**Comment by equation314** [comment]
Hi memN0ps, thanks for your interest in ArceOS.

Currently, `axalloc` has many ArceOS-specified dependencies and is not ready to be published to crates.io.

You can use the following lines to import `axalloc` as a dependency (as said in [README.md](https://github.com/arceos-org/arceos?tab=readme-ov-file#how-to-reuse-arceos-cratesmodules-in-your-own-project)):

```toml
[dependencies]
axalloc = { git = "https://github.com/arceos-org/arceos.git" }
```

**Comment by memN0ps** [comment]
Thank you for letting me know! I look forward to seeing `axalloc`; in the meantime, I'll use the above.
