### ISSUE TITLE
error of compiling C apps  in riscv64 AND aarch64 ARCH 

### ISSUE THREAD

**Issue by chyyuu** [arceos-org/arceos#37]
$ make A=apps/c/helloworld ARCH=riscv64 run
.......
rust-lld -flavor gnu -nostdlib -static -no-pie --gc-sections -T/home/chyyuu/thecodes/arceos/modules/axhal/linker_riscv64.lds apps/c/helloworld/main.o ulib/c_libax/build_riscv64/libc.a target/riscv64gc-unknown-none-elf/release/liblibax.a -o apps/c/helloworld/helloworld_f
rust-lld: error: ulib/c_libax/build_riscv64/libc.a(stat.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_riscv64/libc.a(time.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_riscv64/libc.a(stdlib.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_riscv64/libc.a(fcntl.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_riscv64/libc.a(string.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_riscv64/libc.a(stdio.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_riscv64/libc.a(mmap.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_riscv64/libc.a(unistd.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_riscv64/libc.a(assert.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(libax-99558854f9f72cb2.libax.8f06c8432ac99f28-cgu.0.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(compiler_builtins-8c97496fd8e79463.compiler_builtins.5f3b8f588c381ca5-cgu.0.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(compiler_builtins-8c97496fd8e79463.compiler_builtins.5f3b8f588c381ca5-cgu.1.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(compiler_builtins-8c97496fd8e79463.compiler_builtins.5f3b8f588c381ca5-cgu.10.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(compiler_builtins-8c97496fd8e79463.compiler_builtins.5f3b8f588c381ca5-cgu.11.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(compiler_builtins-8c97496fd8e79463.compiler_builtins.5f3b8f588c381ca5-cgu.12.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(compiler_builtins-8c97496fd8e79463.compiler_builtins.5f3b8f588c381ca5-cgu.13.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(compiler_builtins-8c97496fd8e79463.compiler_builtins.5f3b8f588c381ca5-cgu.14.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(compiler_builtins-8c97496fd8e79463.compiler_builtins.5f3b8f588c381ca5-cgu.15.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(compiler_builtins-8c97496fd8e79463.compiler_builtins.5f3b8f588c381ca5-cgu.2.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/riscv64gc-unknown-none-elf/release/liblibax.a(compiler_builtins-8c97496fd8e79463.compiler_builtins.5f3b8f588c381ca5-cgu.3.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
make: *** [ulib/c_libax/build.mk:74: apps/c/helloworld/helloworld_qemu-virt-riscv.elf] Error 1

$ make A=apps/c/helloworld ARCH=aarch64  run
......
rm -f ulib/c_libax/build_aarch64/libc.a
aarch64-linux-musl-ar rc ulib/c_libax/build_aarch64/libc.a ulib/c_libax/build_aarch64/stat.o ulib/c_libax/build_aarch64/time.o ulib/c_libax/build_aarch64/stdlib.o ulib/c_libax/build_aarch64/fcntl.o ulib/c_libax/build_aarch64/string.o ulib/c_libax/build_aarch64/stdio.o o
aarch64-linux-musl-ranlib ulib/c_libax/build_aarch64/libc.a
    Linking apps/c/helloworld/helloworld_qemu-virt-aarch64.elf
rust-lld -flavor gnu -nostdlib -static -no-pie --gc-sections -T/home/chyyuu/thecodes/arceos/modules/axhal/linker_aarch64.lds apps/c/helloworld/main.o ulib/c_libax/build_aarch64/libc.a target/aarch64-unknown-none-softfloat/release/liblibax.a -o apps/c/helloworld/hellowof
rust-lld: error: ulib/c_libax/build_aarch64/libc.a(stat.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_aarch64/libc.a(time.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_aarch64/libc.a(stdlib.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_aarch64/libc.a(fcntl.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_aarch64/libc.a(string.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_aarch64/libc.a(stdio.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_aarch64/libc.a(mmap.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_aarch64/libc.a(unistd.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: ulib/c_libax/build_aarch64/libc.a(assert.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(libax-3c217168e80c2c7b.libax.e636c8b0142bf204-cgu.1.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(compiler_builtins-164467728415cd01.compiler_builtins.a3c2a0a8e451691c-cgu.0.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(compiler_builtins-164467728415cd01.compiler_builtins.a3c2a0a8e451691c-cgu.1.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(compiler_builtins-164467728415cd01.compiler_builtins.a3c2a0a8e451691c-cgu.10.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(compiler_builtins-164467728415cd01.compiler_builtins.a3c2a0a8e451691c-cgu.11.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(compiler_builtins-164467728415cd01.compiler_builtins.a3c2a0a8e451691c-cgu.12.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(compiler_builtins-164467728415cd01.compiler_builtins.a3c2a0a8e451691c-cgu.13.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(compiler_builtins-164467728415cd01.compiler_builtins.a3c2a0a8e451691c-cgu.14.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(compiler_builtins-164467728415cd01.compiler_builtins.a3c2a0a8e451691c-cgu.15.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(compiler_builtins-164467728415cd01.compiler_builtins.a3c2a0a8e451691c-cgu.2.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: target/aarch64-unknown-none-softfloat/release/liblibax.a(compiler_builtins-164467728415cd01.compiler_builtins.a3c2a0a8e451691c-cgu.3.rcgu.o) is incompatible with apps/c/helloworld/main.o
rust-lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
make: *** [ulib/c_libax/build.mk:74: apps/c/helloworld/helloworld_qemu-virt-aarch64.elf] Error 1

BUT x86_64 ARCH can build and run correctly.

**Comment by equation314** [comment]
Run `make A=apps/c/helloworld clean_c` before switching architecture.

**Comment by chyyuu** [comment]
The right building way:

```
make A=apps/c/helloworld ARCH=riscv64 clean
make A=apps/c/helloworld ARCH=riscv64 run
```
OR
```
make A=apps/c/helloworld ARCH=aarch64 clean
make A=apps/c/helloworld ARCH=aarch64 run
```

Then everything is OK!
