### ISSUE TITLE
Tracking issue: merge features from Azure-stars 

### ISSUE THREAD

**Issue by WenyXu** [arceos-org/arceos#45]
I'm trying to merge [10a536f](https://github.com/WenyXu/arceos/commit/10a536fa988dd6eccdb9ad58d9d8f1f6f3ab287a) from [eb18704](https://github.com/WenyXu/arceos/pull/2/commits/eb187044027077962fde50619742b24af0ad5aab). All changes can be found [here](https://github.com/WenyXu/arceos/pull/2/files).  And I'm refactoring packages in eb18704 , starting from the leaf node of the dependencies graph. 
I will keep following up on updates of both repositories. Please don't hesitate to reach out to me.

```mermaid
graph TD;
axsync-->axdisplay
axdriver-->axdisplay

axhal-->axdriver
axalloc-->axdriver
axconfig-->axdriver

axdriver-->axfs
axsync-->axfs
axtask-.dev.->axfs

axtask-->axfs_os
axfs-->axfs_os

axconfig-->axhal
axalloc-->axhal
axlog-->axhal

axhal-->axnet
axsync-->axnet
axtask-->axnet
axdriver-->axnet

axalloc-->axruntime
axconfig-->axruntime
axdriver-->axruntime
axhal-->axruntime
axlog-->axruntime
axnet-->axruntime
axdisplay-->axruntime
axtask-->axruntime
axprocess-->axruntime
axtask-->axsync
axtask-->axprocess
axfs_os-->axprocess
axhal-->axprocess

axprocess-->axsyscall
axsyscall-->axruntime
axalloc-->axtask
axhal-->axtask
axconfig-->axtask
axlog-->axtask

axhal-->axmem
axalloc-->axmem

axmem-->axprocess

```

Pic from [week10](https://github.com/Azure-stars/arceos/blob/a5305ce4ac0e18bb9721d80ce2ca3729ad1b948f/doc/Week10.md?plain=1#L93)

## Tasks
- Common
  - #44 
-  axprocess
   - axfs_os #46
   - axmem (WIP)
   - axtask
-  ... Updates later

**Comment by chyyuu** [comment]
@WenyXu Good work!  #46 missing doc error.
